var lookup = 
{
	'AD': 'Ashford IECC A',
	'A2': 'Ashford IECC B',
	'A3': 'Ashford Front-End TD',
	'AL': 'Alnmouth',
	'AN': 'Allington Junction',
	'AS': 'Aston',
	'AW': 'Acton Wells',
	'BA': 'Barnsley',
	'BD': 'Bowesfield',
	'BE': 'Basingstoke',
	'BL': 'Bristol',
	'BM': 'Barnham',
	'BN': 'Birmingham New Street',
	'BS': 'Barnes',
	'BX': 'Basingstoke (WoE)',
	'C1': 'SWCC Newport ITD',
	'C2': 'SWCC Vale of Glamorgan ITD',
	'C3': 'SWCC Shrewsbury North WestCAD',
	'CA': 'Cambridge PSB',
	'CC': 'Colchester',
	'CD': 'Castleford',
	'CE': 'Crewe PSB',
	'CF': 'Cardiff',
	'CH': 'Chichester',
	'CL': 'Carlisle',
	'CM': 'Carmuirs East',
	'CS': 'Chester',
	'CT': 'Channel Tunnel',
	'CV': 'Cherwell Valley (Dec 2015)',
	'CY': 'WMCC Coventry',
	'D1': 'TVSC Reading IECC A',
	'D2': 'TVSC Reading IECC B',
	'D3': 'TVSC Paddington IECC',
	'D4': 'TVSC Hayes IECC',
	'D5': 'TVSC Didcot IECC',
	'D6': 'TBA',
	'D7': 'TVSC Swindon IECC',
	'D8': 'TBA',
	'D9': 'TBA',
	'DN': 'Not commissioned',
	'DR': 'Doncaster',
	'DY': 'Derby',
	'E1': 'Edgeley No 1',
	'EA': 'Edinburgh IECC A',
	'EB': 'Edinburgh IECC B',
	'EC': 'Edinburgh IECC C',
	'ED': 'Edinburgh IECC D (planned)',
	'EH': 'Eastleigh',
	'EK': 'East Kent (Gillingham)',
	'EN': 'Cambridge IECC',
	'ES': 'TBROC East Sussex MCS',
	'EX': 'Exeter',
	'FE': 'Ferrybridge',
	'FH': 'Feltham',
	'G1': 'WSSC Glasgow',
	'G2': 'WSSC Paisley',
	'GC': 'WSSC Glasgow',
	'GD': 'Guildford',
	'GL': 'Gloucester ITD',
	'HG': 'Harrogate IECC',
	'HM': 'Healey Mills',
	'HN': 'Heaton Norris',
	'HT': 'Havant',
	'HU': 'Huddersfield',
	'K2': 'Kings Cross (Hertford Loop)',
	'KX': 'Kings Cross',
	'LA': 'Lancing',
	'LB': 'London Bridge',
	'LC': 'WMCC Leamington Corridor',
	'LE': 'Leamington Spa',
	'LN': 'Lincoln',
	'LR': 'EMCC Leicester',
	'LS': 'Liverpool Street',
	'MA': 'Maidstone East',
	'MD': 'EMCC Mansfield',
	'ME': 'Marylebone IECC',
	'MH': 'Machynlleth',
	'ML': 'Motherwell',
	'MO': 'Morpeth',
	'MP': 'Manchester Piccadilly',
	'MS': 'Manchester South',
	'MZ': 'Manchester East',
	'NE': 'EMCC Erewash',
	'NK': 'North Kent',
	'NM': 'EMCC Nottingham',
	'NT': 'TBA',
	'NX': 'New Cross Gate',
	'OX': 'Oxford',
	'PB': 'Peterborough',
	'PH': 'Plymouth',
	'PT': 'Port Talbot',
	'PX': 'Preston',
	'R1': 'Rugby SCC (Watford - Bletchley ITD)',
	'R2': 'Rugby SCC (Northampton - Rugby ITD)',
	'RA': 'Radyr',
	'RT': 'Ridgmont',
	'RW': 'Rochdale West',
	'SA': 'Saltley',
	'SC': 'Scunthorpe',
	'SD': 'Sheffield',
	'SE': 'Shenfield IECC',
	'SH': 'Slough A',
	'SI': 'Stratford IECC',
	'SK': 'Stoke On Trent',
	'SM': 'Stirling Middle',
	'SN': 'Swindon A ITD',
	'SO': 'South Tottenham',
	'SS': 'Merseyrail IECC',
	'SU': 'Surbiton (Woking)',
	'SX': 'Saxmundham MCS',
	'T1': 'Tyneside 1 IECC',
	'T2': 'Tyneside 2 IECC',
	'TB': 'Three Bridges',
	'TD': 'WMCC Telford',
	'TE': 'Tonbridge',
	'TH': 'Thrumpton',
	'TN': 'EMCC Chesterfield',
	'TW': 'Tweedmouth',
	'TY': 'Tees Yard (Ryhope)',
	'U2': 'Upminster 2 IECC',
	'U3': 'Upminster 3 IECC',
	'UR': 'Upminster A IECC',
	'VC': 'London Victoria',
	'VT': 'Thameslink South',
	'WA': 'Warrington PSB',
	'WD': 'Winsford',
	'WE': 'Worksop',
	'WG': 'West Anglia IECC',
	'WH': 'West Hampstead PSB',
	'WI': 'Wimbledon NCP',
	'WJ': 'Watford Junction',
	'WK': 'Wakefield Kirkgate',
	'WN': 'WMCC Water Orton',
	'WO': 'Wolverhampton PSB',
	'WS': 'Willesden Suburban',
	'WT': 'Thameslink North',
	'WW': 'Westbury',
	'WY': 'Wembley',
	'XB': 'Macclesfield',
	'XE': 'Warrington Central',
	'XH': 'Stafford No 4',
	'XJ': 'Stafford No 5',
	'XL': 'Hunts Cross',
	'XP': 'Manchester North',
	'XZ': 'Liverpool Lime Street',
	'Y2': 'York IECC 2',
	'Y3': 'York IECC 3',
	'YK': 'York IECC',
	'YO': 'Yoker IECC',
	'ZA': 'Ashford TDC',
	'ZB': 'Bournemouth TDC',
	'ZE': 'Eastbourne TDC',
	'ZG': 'Guildford TDC',
	'ZH': 'Horsham TDC',
	'ZR': 'Rainham TDC',
	'ZY': 'Yeovil TDC'
}

module.exports = lookup
